interface Slide {
  desktopSrc: string;
  mobileSrc: string;
  alt: string;
  title: string;
  subtitle?: string;
}

export const heroData: Slide[] = [
  {
    desktopSrc:
      "/images/hero/inner-banner.webp",
    mobileSrc:
      "/images/hero/inner-banner.webp",
    alt: "Spring Collection",
    title: "SEO-Friendly SSR",
    subtitle: "Fast initial paint",
  },
  {
    desktopSrc:
      "/images/hero/fashion-collection-hanging-in-modern-clothing-store-free-photo.jpg",
    mobileSrc:
      "/images/hero/fashion-collection-hanging-in-modern-clothing-store-free-photo.jpg",
    alt: "Kids Collection",
    title: "Welcome to Our Site",
    subtitle: "Discover awesome features",
  },
  {
    desktopSrc: "/images/hero/TPWW.webp",
    mobileSrc: "/images/hero/TPWW.webp",
    alt: "Menswear Collection",
    title: "Built with Tailwind CSS",
    subtitle: "Utility-first styling",
  },
  // {
  //   desktopSrc:
  //     "/images/hero/collage-photos-young-people-fashion-260nw-1724618176.webp",
  //   mobileSrc:
  //     "/images/hero/collage-photos-young-people-fashion-260nw-1724618176.webp",
  //   alt: "Spring Collection",
  //   title: "SEO-Friendly SSR",
  //   subtitle: "Fast initial paint",
  // },
  
  // {
  //   desktopSrc:
  //     "/images/hero/group-different-men-women-on-260nw-2477681591.webp",
  //   mobileSrc:
  //     "/images/hero/group-different-men-women-on-260nw-2477681591.webp",
  //   alt: "Spring Collection",
  //   title: "SEO-Friendly SSR",
  //   subtitle: "Fast initial paint",
  // },
];

export const navItems = [
  { label: "Home", href: "/" },
  {
    label: "Men",
    href: "/category/men",
    children: [
      { label: "Boxers", href: "/sub_category/boxers" },
      { label: "Men T-Shirts", href: "/sub_category/men-t-shirts" },
    ],
  },
  {
    label: "Women",
    href: "/category/women",
    children: [
      { label: "Boxers", href: "/sub_category/boxers1" },
      { label: "Women T-Shirts", href: "/sub_category/men-t-shirts1" },
    ],
  },
  { label: "Juniors", href: "/category/juniors" },
  { label: "New Arrivals", href: "/categry/new-arrivals" },
];

export const slides = [
  {
    title: "Product 1",
    src: "/images/products/Geometric-Spring-7.jpg",
    secSrc: "/images/products/Geometric-Spring-5.jpg",
    alt: "Light-patterned pajama",
    id: 1,
    price: "1229.99",
    href: "/product1",
    rating: 4.5,
    oldPrice: "1239.99",
    discount: "25% off",
  },
  {
    title: "Product 2",
    src: "/images/products/Paul_4.jpeg",
    secSrc: "/images/products/Paul_1.jpeg",
    alt: "Blue tee & checkered shorts",
    id: 2,
    price: "1229.99",
    href: "/product2",
    rating: 3.5,
    oldPrice: "1239.99",
    discount: "25% off",
  },
  {
    title: "Product 3",
    src: "/images/products/Sam.jpeg",
    secSrc: "/images/products/Sam_3.jpeg",
    alt: "White tee & dark shorts",
    id: 3,
    price: "1229.99",
    href: "/product3",
    rating: 4.5,
    oldPrice: "1239.99",
    discount: "25% off",
  },
  {
    title: "Product 4",
    src: "/images/products/Snoozeoff0321.jpeg",
    secSrc: "/images/products/Secret-Garden.jpg",
    alt: "White tee & dark shorts",
    id: 4,
    price: "1229.99",
    href: "/product4",
    rating: 4.5,
    oldPrice: "1239.99",
    discount: "25% off",
  },
  {
    title: "Product 5",
    src: "/images/products/SnuggleBear.jpg",
    secSrc: "/images/products/SnuggleBear1.jpg",
    alt: "White tee & dark shorts",
    id: 5,
    price: "1229.99",
    href: "/product5",
    rating: 4.5,
    oldPrice: "1239.99",
    discount: "25% off",
  },
  {
    title: "Product 6",
    src: "/images/products/Taffy_Navy_Pajama_Sets.jpg",
    secSrc: "/images/products/Taffy_Navy_Pajama_Set.jpg",
    alt: "White tee & dark shorts",
    id: 6,
    price: "1229.99",
    href: "/product6",
    rating: 3.5,
    oldPrice: "1239.99",
    discount: "25% off",
  },
];

export const products = [
  {
    createdAt: "2025-07-23T14:52:40.178Z",
    id: 1,
    documentId: "qo48kfmsezck2uqxxx063tzo",
    name: "Pack of Two (Black + White)",
    description:
      "Upgrade your intimate essentials with our pack of two men’s boxers, featuring navy blue and grey colou Designed with BCL cotton, 10% elastane and 100% cotton, our men’s boxers ensure maximum breathability and flexibility. These boxers are made from 90% cotton and 10% elastance that guarantees a perfect fit, making them a go-to choice for your comfort and durability.",
    slug: "pack-of-two-black-white",
    discount_price: null,
    price: 2799,
    is_feature: false,
    views: 0,
    sales: 0,
    updatedAt: "2025-07-23T14:52:40.178Z",
    publishedAt: "2025-07-23T14:52:40.102Z",
    images: [
      {
        id: 3,
        documentId: "qz70g6sejzpfnq857cr7vtqa",
        formats: {
          small: {
            ext: ".webp",
            url: "/uploads/small_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1.webp",
            hash: "small_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1",
            mime: "image/webp",
            name: "small_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey.webp",
            path: null,
            size: 8.63,
            width: 333,
            height: 500,
            sizeInBytes: 8626,
          },
          thumbnail: {
            ext: ".webp",
            url: "/uploads/thumbnail_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1.webp",
            hash: "thumbnail_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1",
            mime: "image/webp",
            name: "thumbnail_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey.webp",
            path: null,
            size: 1.86,
            width: 104,
            height: 156,
            sizeInBytes: 1862,
          },
        },
      },
      {
        id: 4,
        documentId: "vqhb3s9oh8kyr2kx0ikgrs3c",
        formats: {
          small: {
            ext: ".webp",
            url: "/uploads/small_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306.webp",
            hash: "small_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306",
            mime: "image/webp",
            name: "small_Navy_Blue_Grey_Men_s_Boxer_Set.webp",
            path: null,
            size: 5.17,
            width: 333,
            height: 500,
            sizeInBytes: 5172,
          },
          thumbnail: {
            ext: ".webp",
            url: "/uploads/thumbnail_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306.webp",
            hash: "thumbnail_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306",
            mime: "image/webp",
            name: "thumbnail_Navy_Blue_Grey_Men_s_Boxer_Set.webp",
            path: null,
            size: 1.02,
            width: 104,
            height: 156,
            sizeInBytes: 1024,
          },
        },
      },
    ],
    variants: [
      {
        id: 1,
        documentId: "jcc2a58a5zvdtexqdygy0f6r",
        size: "XS",
        sku: "DFM-BX-C-0001/BLACK-WHITE-XS",
        price: 2799,
        basePrice: null,
        createdAt: "2025-07-23T14:40:51.352Z",
        updatedAt: "2025-07-23T14:43:18.326Z",
        publishedAt: "2025-07-23T14:43:18.179Z",
      },
      {
        id: 2,
        documentId: "gsdg5v4lmxusflpy2zn1xivo",
        size: "S",
        sku: "DFM-BX-C-0001/BLACK-WHITE-S",
        price: 2700,
        basePrice: null,
        createdAt: "2025-07-23T14:47:29.620Z",
        updatedAt: "2025-07-23T14:47:29.620Z",
        publishedAt: "2025-07-23T14:47:29.518Z",
      },
      {
        id: 3,
        documentId: "fibzacz760nj0an1g582t98h",
        size: "M",
        sku: "DFM-BX-C-0001/BLACK-WHITE-M",
        price: 2700,
        basePrice: null,
        createdAt: "2025-07-23T14:48:11.778Z",
        updatedAt: "2025-07-23T14:48:11.778Z",
        publishedAt: "2025-07-23T14:48:11.707Z",
      },
      {
        id: 4,
        documentId: "ye6dkimqn2sfzws5o0kw5lxe",
        size: "L",
        sku: "DFM-BX-C-0001/BLACK-WHITE-L",
        price: 2799,
        basePrice: null,
        createdAt: "2025-07-23T14:48:42.409Z",
        updatedAt: "2025-07-23T14:48:42.409Z",
        publishedAt: "2025-07-23T14:48:42.340Z",
      },
    ],
  },
  {
    createdAt: "2025-07-23T14:52:40.178Z",
    id: 2,
    documentId: "qo48kfmsezck2uqxxx063tzo",
    name: "Pack of Two (Black + White)",
    description:
      "Upgrade your intimate essentials with our pack of two men’s boxers, featuring navy blue and grey colou Designed with BCL cotton, 10% elastane and 100% cotton, our men’s boxers ensure maximum breathability and flexibility. These boxers are made from 90% cotton and 10% elastance that guarantees a perfect fit, making them a go-to choice for your comfort and durability.",
    slug: "pack-of-two-black-white",
    discount_price: null,
    price: 2799,
    is_feature: false,
    views: 0,
    sales: 0,
    updatedAt: "2025-07-23T14:52:40.178Z",
    publishedAt: "2025-07-23T14:52:40.102Z",
    images: [
      {
        id: 3,
        documentId: "qz70g6sejzpfnq857cr7vtqa",
        formats: {
          small: {
            ext: ".webp",
            url: "/uploads/small_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1.webp",
            hash: "small_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1",
            mime: "image/webp",
            name: "small_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey.webp",
            path: null,
            size: 8.63,
            width: 333,
            height: 500,
            sizeInBytes: 8626,
          },
          thumbnail: {
            ext: ".webp",
            url: "/uploads/thumbnail_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1.webp",
            hash: "thumbnail_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1",
            mime: "image/webp",
            name: "thumbnail_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey.webp",
            path: null,
            size: 1.86,
            width: 104,
            height: 156,
            sizeInBytes: 1862,
          },
        },
      },
      {
        id: 4,
        documentId: "vqhb3s9oh8kyr2kx0ikgrs3c",
        formats: {
          small: {
            ext: ".webp",
            url: "/uploads/small_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306.webp",
            hash: "small_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306",
            mime: "image/webp",
            name: "small_Navy_Blue_Grey_Men_s_Boxer_Set.webp",
            path: null,
            size: 5.17,
            width: 333,
            height: 500,
            sizeInBytes: 5172,
          },
          thumbnail: {
            ext: ".webp",
            url: "/uploads/thumbnail_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306.webp",
            hash: "thumbnail_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306",
            mime: "image/webp",
            name: "thumbnail_Navy_Blue_Grey_Men_s_Boxer_Set.webp",
            path: null,
            size: 1.02,
            width: 104,
            height: 156,
            sizeInBytes: 1024,
          },
        },
      },
    ],
    variants: [
      {
        id: 1,
        documentId: "jcc2a58a5zvdtexqdygy0f6r",
        size: "XS",
        sku: "DFM-BX-C-0001/BLACK-WHITE-XS",
        price: 2799,
        basePrice: null,
        createdAt: "2025-07-23T14:40:51.352Z",
        updatedAt: "2025-07-23T14:43:18.326Z",
        publishedAt: "2025-07-23T14:43:18.179Z",
      },
      {
        id: 2,
        documentId: "gsdg5v4lmxusflpy2zn1xivo",
        size: "S",
        sku: "DFM-BX-C-0001/BLACK-WHITE-S",
        price: 2700,
        basePrice: null,
        createdAt: "2025-07-23T14:47:29.620Z",
        updatedAt: "2025-07-23T14:47:29.620Z",
        publishedAt: "2025-07-23T14:47:29.518Z",
      },
      {
        id: 3,
        documentId: "fibzacz760nj0an1g582t98h",
        size: "M",
        sku: "DFM-BX-C-0001/BLACK-WHITE-M",
        price: 2700,
        basePrice: null,
        createdAt: "2025-07-23T14:48:11.778Z",
        updatedAt: "2025-07-23T14:48:11.778Z",
        publishedAt: "2025-07-23T14:48:11.707Z",
      },
      {
        id: 4,
        documentId: "ye6dkimqn2sfzws5o0kw5lxe",
        size: "L",
        sku: "DFM-BX-C-0001/BLACK-WHITE-L",
        price: 2799,
        basePrice: null,
        createdAt: "2025-07-23T14:48:42.409Z",
        updatedAt: "2025-07-23T14:48:42.409Z",
        publishedAt: "2025-07-23T14:48:42.340Z",
      },
    ],
  },
  {
    createdAt: "2025-07-23T14:52:40.178Z",
    id: 3,
    documentId: "qo48kfmsezck2uqxxx063tzo",
    name: "Pack of Two (Black + White)",
    description:
      "Upgrade your intimate essentials with our pack of two men’s boxers, featuring navy blue and grey colou Designed with BCL cotton, 10% elastane and 100% cotton, our men’s boxers ensure maximum breathability and flexibility. These boxers are made from 90% cotton and 10% elastance that guarantees a perfect fit, making them a go-to choice for your comfort and durability.",
    slug: "pack-of-two-black-white",
    discount_price: null,
    price: 2799,
    is_feature: false,
    views: 0,
    sales: 0,
    updatedAt: "2025-07-23T14:52:40.178Z",
    publishedAt: "2025-07-23T14:52:40.102Z",
    images: [
      {
        id: 3,
        documentId: "qz70g6sejzpfnq857cr7vtqa",
        formats: {
          small: {
            ext: ".webp",
            url: "/uploads/small_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1.webp",
            hash: "small_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1",
            mime: "image/webp",
            name: "small_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey.webp",
            path: null,
            size: 8.63,
            width: 333,
            height: 500,
            sizeInBytes: 8626,
          },
          thumbnail: {
            ext: ".webp",
            url: "/uploads/thumbnail_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1.webp",
            hash: "thumbnail_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1",
            mime: "image/webp",
            name: "thumbnail_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey.webp",
            path: null,
            size: 1.86,
            width: 104,
            height: 156,
            sizeInBytes: 1862,
          },
        },
      },
      {
        id: 4,
        documentId: "vqhb3s9oh8kyr2kx0ikgrs3c",
        formats: {
          small: {
            ext: ".webp",
            url: "/uploads/small_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306.webp",
            hash: "small_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306",
            mime: "image/webp",
            name: "small_Navy_Blue_Grey_Men_s_Boxer_Set.webp",
            path: null,
            size: 5.17,
            width: 333,
            height: 500,
            sizeInBytes: 5172,
          },
          thumbnail: {
            ext: ".webp",
            url: "/uploads/thumbnail_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306.webp",
            hash: "thumbnail_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306",
            mime: "image/webp",
            name: "thumbnail_Navy_Blue_Grey_Men_s_Boxer_Set.webp",
            path: null,
            size: 1.02,
            width: 104,
            height: 156,
            sizeInBytes: 1024,
          },
        },
      },
    ],
    variants: [
      {
        id: 1,
        documentId: "jcc2a58a5zvdtexqdygy0f6r",
        size: "XS",
        sku: "DFM-BX-C-0001/BLACK-WHITE-XS",
        price: 2799,
        basePrice: null,
        createdAt: "2025-07-23T14:40:51.352Z",
        updatedAt: "2025-07-23T14:43:18.326Z",
        publishedAt: "2025-07-23T14:43:18.179Z",
      },
      {
        id: 2,
        documentId: "gsdg5v4lmxusflpy2zn1xivo",
        size: "S",
        sku: "DFM-BX-C-0001/BLACK-WHITE-S",
        price: 2700,
        basePrice: null,
        createdAt: "2025-07-23T14:47:29.620Z",
        updatedAt: "2025-07-23T14:47:29.620Z",
        publishedAt: "2025-07-23T14:47:29.518Z",
      },
      {
        id: 3,
        documentId: "fibzacz760nj0an1g582t98h",
        size: "M",
        sku: "DFM-BX-C-0001/BLACK-WHITE-M",
        price: 2700,
        basePrice: null,
        createdAt: "2025-07-23T14:48:11.778Z",
        updatedAt: "2025-07-23T14:48:11.778Z",
        publishedAt: "2025-07-23T14:48:11.707Z",
      },
      {
        id: 4,
        documentId: "ye6dkimqn2sfzws5o0kw5lxe",
        size: "L",
        sku: "DFM-BX-C-0001/BLACK-WHITE-L",
        price: 2799,
        basePrice: null,
        createdAt: "2025-07-23T14:48:42.409Z",
        updatedAt: "2025-07-23T14:48:42.409Z",
        publishedAt: "2025-07-23T14:48:42.340Z",
      },
    ],
  },
  {
    createdAt: "2025-07-23T14:52:40.178Z",
    id: 4,
    documentId: "qo48kfmsezck2uqxxx063tzo",
    name: "Pack of Two (Black + White)",
    description:
      "Upgrade your intimate essentials with our pack of two men’s boxers, featuring navy blue and grey colou Designed with BCL cotton, 10% elastane and 100% cotton, our men’s boxers ensure maximum breathability and flexibility. These boxers are made from 90% cotton and 10% elastance that guarantees a perfect fit, making them a go-to choice for your comfort and durability.",
    slug: "pack-of-two-black-white",
    discount_price: null,
    price: 2799,
    is_feature: false,
    views: 0,
    sales: 0,
    updatedAt: "2025-07-23T14:52:40.178Z",
    publishedAt: "2025-07-23T14:52:40.102Z",
    images: [
      {
        id: 3,
        documentId: "qz70g6sejzpfnq857cr7vtqa",
        formats: {
          small: {
            ext: ".webp",
            url: "/uploads/small_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1.webp",
            hash: "small_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1",
            mime: "image/webp",
            name: "small_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey.webp",
            path: null,
            size: 8.63,
            width: 333,
            height: 500,
            sizeInBytes: 8626,
          },
          thumbnail: {
            ext: ".webp",
            url: "/uploads/thumbnail_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1.webp",
            hash: "thumbnail_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey_864a4984c1",
            mime: "image/webp",
            name: "thumbnail_Pack_of_Two_Men_s_Boxers_Navy_Blue_Grey.webp",
            path: null,
            size: 1.86,
            width: 104,
            height: 156,
            sizeInBytes: 1862,
          },
        },
      },
      {
        id: 4,
        documentId: "vqhb3s9oh8kyr2kx0ikgrs3c",
        formats: {
          small: {
            ext: ".webp",
            url: "/uploads/small_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306.webp",
            hash: "small_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306",
            mime: "image/webp",
            name: "small_Navy_Blue_Grey_Men_s_Boxer_Set.webp",
            path: null,
            size: 5.17,
            width: 333,
            height: 500,
            sizeInBytes: 5172,
          },
          thumbnail: {
            ext: ".webp",
            url: "/uploads/thumbnail_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306.webp",
            hash: "thumbnail_Navy_Blue_Grey_Men_s_Boxer_Set_0ae00e0306",
            mime: "image/webp",
            name: "thumbnail_Navy_Blue_Grey_Men_s_Boxer_Set.webp",
            path: null,
            size: 1.02,
            width: 104,
            height: 156,
            sizeInBytes: 1024,
          },
        },
      },
    ],
    variants: [
      {
        id: 1,
        documentId: "jcc2a58a5zvdtexqdygy0f6r",
        size: "XS",
        sku: "DFM-BX-C-0001/BLACK-WHITE-XS",
        price: 2799,
        basePrice: null,
        createdAt: "2025-07-23T14:40:51.352Z",
        updatedAt: "2025-07-23T14:43:18.326Z",
        publishedAt: "2025-07-23T14:43:18.179Z",
      },
      {
        id: 2,
        documentId: "gsdg5v4lmxusflpy2zn1xivo",
        size: "S",
        sku: "DFM-BX-C-0001/BLACK-WHITE-S",
        price: 2700,
        basePrice: null,
        createdAt: "2025-07-23T14:47:29.620Z",
        updatedAt: "2025-07-23T14:47:29.620Z",
        publishedAt: "2025-07-23T14:47:29.518Z",
      },
      {
        id: 3,
        documentId: "fibzacz760nj0an1g582t98h",
        size: "M",
        sku: "DFM-BX-C-0001/BLACK-WHITE-M",
        price: 2700,
        basePrice: null,
        createdAt: "2025-07-23T14:48:11.778Z",
        updatedAt: "2025-07-23T14:48:11.778Z",
        publishedAt: "2025-07-23T14:48:11.707Z",
      },
      {
        id: 4,
        documentId: "ye6dkimqn2sfzws5o0kw5lxe",
        size: "L",
        sku: "DFM-BX-C-0001/BLACK-WHITE-L",
        price: 2799,
        basePrice: null,
        createdAt: "2025-07-23T14:48:42.409Z",
        updatedAt: "2025-07-23T14:48:42.409Z",
        publishedAt: "2025-07-23T14:48:42.340Z",
      },
    ],
  },
];
